name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Clean install dependencies
      run: |
        rm -f package-lock.json
        npm install --no-package-lock
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type check
      run: npx tsc --noEmit
    
    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_PROJECT_ID: fe515ff9704eef45dac867b8e313317d

    - name: Success message
      run: echo "✅ Build completed successfully! Project is ready for deployment."